# Setup
title: Your Website Title
tagline: Your Website Tagline
url: https://devpractical.com
paginate: 3
baseurl: ""
permalink: pretty
theme: jekyll-theme-minimal

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Max Miner
  url: https://https://twitter.com/mxmnr

# Custom vars
version: 3.0.0